services:
  converter-heggland:
    build: ./
    container_name: converter.heggland.tech
    networks:
      - nginx-app-network
    restart: always

networks:
  nginx-app-network:
    external: true
